// The complete country list for the global CountryBadge switcher — every
// sovereign/commonly-listed territory, not just the curated investment
// markets shown on the /countries marketing page (see geoCountries.ts,
// which stays scoped to that page's descriptions and is a separate,
// deliberately smaller list). `flag` is the lowercase ISO 3166-1 alpha-2
// code used by flagcdn.com (https://flagcdn.com/w40/{flag}.png).
export type Country = { name: string; flag: string };
export type CountryRegion = { name: string; countries: Country[] };

export const ALL_COUNTRY_REGIONS: CountryRegion[] = [
  {
    name: 'Europe',
    countries: [
      { name: 'United Kingdom', flag: 'gb' },
      { name: 'Albania', flag: 'al' },
      { name: 'Andorra', flag: 'ad' },
      { name: 'Austria', flag: 'at' },
      { name: 'Belarus', flag: 'by' },
      { name: 'Belgium', flag: 'be' },
      { name: 'Bosnia and Herzegovina', flag: 'ba' },
      { name: 'Bulgaria', flag: 'bg' },
      { name: 'Croatia', flag: 'hr' },
      { name: 'Cyprus', flag: 'cy' },
      { name: 'Czech Republic', flag: 'cz' },
      { name: 'Denmark', flag: 'dk' },
      { name: 'Estonia', flag: 'ee' },
      { name: 'Finland', flag: 'fi' },
      { name: 'France', flag: 'fr' },
      { name: 'Germany', flag: 'de' },
      { name: 'Greece', flag: 'gr' },
      { name: 'Hungary', flag: 'hu' },
      { name: 'Iceland', flag: 'is' },
      { name: 'Ireland', flag: 'ie' },
      { name: 'Italy', flag: 'it' },
      { name: 'Kosovo', flag: 'xk' },
      { name: 'Latvia', flag: 'lv' },
      { name: 'Liechtenstein', flag: 'li' },
      { name: 'Lithuania', flag: 'lt' },
      { name: 'Luxembourg', flag: 'lu' },
      { name: 'Malta', flag: 'mt' },
      { name: 'Moldova', flag: 'md' },
      { name: 'Monaco', flag: 'mc' },
      { name: 'Montenegro', flag: 'me' },
      { name: 'Netherlands', flag: 'nl' },
      { name: 'North Macedonia', flag: 'mk' },
      { name: 'Norway', flag: 'no' },
      { name: 'Poland', flag: 'pl' },
      { name: 'Portugal', flag: 'pt' },
      { name: 'Romania', flag: 'ro' },
      { name: 'Russia', flag: 'ru' },
      { name: 'San Marino', flag: 'sm' },
      { name: 'Serbia', flag: 'rs' },
      { name: 'Slovakia', flag: 'sk' },
      { name: 'Slovenia', flag: 'si' },
      { name: 'Spain', flag: 'es' },
      { name: 'Sweden', flag: 'se' },
      { name: 'Switzerland', flag: 'ch' },
      { name: 'Ukraine', flag: 'ua' },
      { name: 'Vatican City', flag: 'va' },
    ],
  },
  {
    name: 'Middle East',
    countries: [
      { name: 'Armenia', flag: 'am' },
      { name: 'Azerbaijan', flag: 'az' },
      { name: 'Bahrain', flag: 'bh' },
      { name: 'Georgia', flag: 'ge' },
      { name: 'Iran', flag: 'ir' },
      { name: 'Iraq', flag: 'iq' },
      { name: 'Israel', flag: 'il' },
      { name: 'Jordan', flag: 'jo' },
      { name: 'Kuwait', flag: 'kw' },
      { name: 'Lebanon', flag: 'lb' },
      { name: 'Oman', flag: 'om' },
      { name: 'Palestine', flag: 'ps' },
      { name: 'Qatar', flag: 'qa' },
      { name: 'Saudi Arabia', flag: 'sa' },
      { name: 'Syria', flag: 'sy' },
      { name: 'Turkey', flag: 'tr' },
      { name: 'United Arab Emirates', flag: 'ae' },
      { name: 'Yemen', flag: 'ye' },
    ],
  },
  {
    name: 'Americas',
    countries: [
      { name: 'United States', flag: 'us' },
      { name: 'Canada', flag: 'ca' },
      { name: 'Mexico', flag: 'mx' },
      { name: 'Antigua and Barbuda', flag: 'ag' },
      { name: 'Argentina', flag: 'ar' },
      { name: 'Bahamas', flag: 'bs' },
      { name: 'Barbados', flag: 'bb' },
      { name: 'Belize', flag: 'bz' },
      { name: 'Bolivia', flag: 'bo' },
      { name: 'Brazil', flag: 'br' },
      { name: 'Chile', flag: 'cl' },
      { name: 'Colombia', flag: 'co' },
      { name: 'Costa Rica', flag: 'cr' },
      { name: 'Cuba', flag: 'cu' },
      { name: 'Dominica', flag: 'dm' },
      { name: 'Dominican Republic', flag: 'do' },
      { name: 'Ecuador', flag: 'ec' },
      { name: 'El Salvador', flag: 'sv' },
      { name: 'Grenada', flag: 'gd' },
      { name: 'Guatemala', flag: 'gt' },
      { name: 'Guyana', flag: 'gy' },
      { name: 'Haiti', flag: 'ht' },
      { name: 'Honduras', flag: 'hn' },
      { name: 'Jamaica', flag: 'jm' },
      { name: 'Nicaragua', flag: 'ni' },
      { name: 'Panama', flag: 'pa' },
      { name: 'Paraguay', flag: 'py' },
      { name: 'Peru', flag: 'pe' },
      { name: 'Saint Kitts and Nevis', flag: 'kn' },
      { name: 'Saint Lucia', flag: 'lc' },
      { name: 'Saint Vincent and the Grenadines', flag: 'vc' },
      { name: 'Suriname', flag: 'sr' },
      { name: 'Trinidad and Tobago', flag: 'tt' },
      { name: 'Uruguay', flag: 'uy' },
      { name: 'Venezuela', flag: 've' },
    ],
  },
  {
    name: 'Asia & Asia-Pacific',
    countries: [
      { name: 'Afghanistan', flag: 'af' },
      { name: 'Bangladesh', flag: 'bd' },
      { name: 'Bhutan', flag: 'bt' },
      { name: 'Brunei', flag: 'bn' },
      { name: 'Cambodia', flag: 'kh' },
      { name: 'China', flag: 'cn' },
      { name: 'Hong Kong', flag: 'hk' },
      { name: 'India', flag: 'in' },
      { name: 'Indonesia', flag: 'id' },
      { name: 'Japan', flag: 'jp' },
      { name: 'Kazakhstan', flag: 'kz' },
      { name: 'Kyrgyzstan', flag: 'kg' },
      { name: 'Laos', flag: 'la' },
      { name: 'Macau', flag: 'mo' },
      { name: 'Malaysia', flag: 'my' },
      { name: 'Maldives', flag: 'mv' },
      { name: 'Mongolia', flag: 'mn' },
      { name: 'Myanmar', flag: 'mm' },
      { name: 'Nepal', flag: 'np' },
      { name: 'North Korea', flag: 'kp' },
      { name: 'Pakistan', flag: 'pk' },
      { name: 'Philippines', flag: 'ph' },
      { name: 'Singapore', flag: 'sg' },
      { name: 'South Korea', flag: 'kr' },
      { name: 'Sri Lanka', flag: 'lk' },
      { name: 'Taiwan', flag: 'tw' },
      { name: 'Tajikistan', flag: 'tj' },
      { name: 'Thailand', flag: 'th' },
      { name: 'Timor-Leste', flag: 'tl' },
      { name: 'Turkmenistan', flag: 'tm' },
      { name: 'Uzbekistan', flag: 'uz' },
      { name: 'Vietnam', flag: 'vn' },
    ],
  },
  {
    name: 'Africa',
    countries: [
      { name: 'Algeria', flag: 'dz' },
      { name: 'Angola', flag: 'ao' },
      { name: 'Benin', flag: 'bj' },
      { name: 'Botswana', flag: 'bw' },
      { name: 'Burkina Faso', flag: 'bf' },
      { name: 'Burundi', flag: 'bi' },
      { name: 'Cabo Verde', flag: 'cv' },
      { name: 'Cameroon', flag: 'cm' },
      { name: 'Central African Republic', flag: 'cf' },
      { name: 'Chad', flag: 'td' },
      { name: 'Comoros', flag: 'km' },
      { name: 'Congo (DR)', flag: 'cd' },
      { name: 'Congo (Republic)', flag: 'cg' },
      { name: 'Djibouti', flag: 'dj' },
      { name: 'Egypt', flag: 'eg' },
      { name: 'Equatorial Guinea', flag: 'gq' },
      { name: 'Eritrea', flag: 'er' },
      { name: 'Eswatini', flag: 'sz' },
      { name: 'Ethiopia', flag: 'et' },
      { name: 'Gabon', flag: 'ga' },
      { name: 'Gambia', flag: 'gm' },
      { name: 'Ghana', flag: 'gh' },
      { name: 'Guinea', flag: 'gn' },
      { name: 'Guinea-Bissau', flag: 'gw' },
      { name: 'Ivory Coast', flag: 'ci' },
      { name: 'Kenya', flag: 'ke' },
      { name: 'Lesotho', flag: 'ls' },
      { name: 'Liberia', flag: 'lr' },
      { name: 'Libya', flag: 'ly' },
      { name: 'Madagascar', flag: 'mg' },
      { name: 'Malawi', flag: 'mw' },
      { name: 'Mali', flag: 'ml' },
      { name: 'Mauritania', flag: 'mr' },
      { name: 'Mauritius', flag: 'mu' },
      { name: 'Morocco', flag: 'ma' },
      { name: 'Mozambique', flag: 'mz' },
      { name: 'Namibia', flag: 'na' },
      { name: 'Niger', flag: 'ne' },
      { name: 'Nigeria', flag: 'ng' },
      { name: 'Rwanda', flag: 'rw' },
      { name: 'Sao Tome and Principe', flag: 'st' },
      { name: 'Senegal', flag: 'sn' },
      { name: 'Seychelles', flag: 'sc' },
      { name: 'Sierra Leone', flag: 'sl' },
      { name: 'Somalia', flag: 'so' },
      { name: 'South Africa', flag: 'za' },
      { name: 'South Sudan', flag: 'ss' },
      { name: 'Sudan', flag: 'sd' },
      { name: 'Tanzania', flag: 'tz' },
      { name: 'Togo', flag: 'tg' },
      { name: 'Tunisia', flag: 'tn' },
      { name: 'Uganda', flag: 'ug' },
      { name: 'Zambia', flag: 'zm' },
      { name: 'Zimbabwe', flag: 'zw' },
    ],
  },
  {
    name: 'Oceania',
    countries: [
      { name: 'Australia', flag: 'au' },
      { name: 'Fiji', flag: 'fj' },
      { name: 'Kiribati', flag: 'ki' },
      { name: 'Marshall Islands', flag: 'mh' },
      { name: 'Micronesia', flag: 'fm' },
      { name: 'Nauru', flag: 'nr' },
      { name: 'New Zealand', flag: 'nz' },
      { name: 'Palau', flag: 'pw' },
      { name: 'Papua New Guinea', flag: 'pg' },
      { name: 'Samoa', flag: 'ws' },
      { name: 'Solomon Islands', flag: 'sb' },
      { name: 'Tonga', flag: 'to' },
      { name: 'Tuvalu', flag: 'tv' },
      { name: 'Vanuatu', flag: 'vu' },
    ],
  },
];
